//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_CHUYEN_KHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_CHUYEN_KHO()
        {
            this.CT_PHIEU_CHUYEN_KHO = new HashSet<CT_PHIEU_CHUYEN_KHO>();
        }
    
        public int ID_PHIEU_CHUYEN_KHO { get; set; }
        public Nullable<int> ID_KHO_XUAT { get; set; }
        public Nullable<int> ID_KHO_NHAN { get; set; }
        public Nullable<int> ID_TK { get; set; }
        public Nullable<System.DateTime> THOI_GIAN_CHUYEN_KHO { get; set; }
        public Nullable<double> TONG_TIEN { get; set; }
        public string GHI_CHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEU_CHUYEN_KHO> CT_PHIEU_CHUYEN_KHO { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual KHO KHO1 { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
