//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAI_KHOAN
    {
        public int ID_TK { get; set; }
        public Nullable<int> ID_LTK { get; set; }
        public string TEN_DANG_NHAP { get; set; }
        public string MAT_KHAU { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual LOAI_TAI_KHOAN LOAI_TAI_KHOAN { get; set; }
    }
}
